Update backup script + add restore-all

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -18,6 +18,8 @@ if [ $? -eq 0 ]; then
     echo 
     
     ./cleanup
+elif [ $? -eq 3 ]; then
+    echo "Backup failed to copy some source files. Exit code 3."
 else
-    echo "Backup failed."
+    echo "Backup failed, see logs."
 fi
